/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza — sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Preview the automatic sector for a description (does not create a ticket)
 */
export const classificationControllerPreviewV1BodyDescriptionMax = 2000;



export const ClassificationControllerPreviewV1Body = zod.object({
  "description": zod.string().min(1).max(classificationControllerPreviewV1BodyDescriptionMax).describe('Free-text problem description (RB-02: text only, never photos)')
})

export const ClassificationControllerPreviewV1Response = zod.object({
  "automatic_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "confidence": zod.number().optional()
})

