/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Create and forward a ticket (Tela A.4 submit)
 */
export const ticketsControllerCreateV1BodyDescriptionMax = 2000;



export const TicketsControllerCreateV1Body = zod.object({
  "description": zod.string().max(ticketsControllerCreateV1BodyDescriptionMax).describe('Descrição do problema em linguagem natural'),
  "location": zod.string().describe('Enviado em multipart/form-data como uma string JSON, ex.: {"building_id":"...","environment_id":"..."}'),
  "automatic_sector_id": zod.uuid().describe('UUID do setor sugerido pela classificação automática'),
  "confirmed_sector_id": zod.uuid().describe('UUID do setor confirmado/escolhido pelo solicitante'),
  "photos": zod.array(zod.instanceof(Blob)).optional().describe('Fotos opcionais (evidência visual - nunca usadas na classificação, RB-02)')
})

export const TicketsControllerCreateV1Response = zod.object({
  "id": zod.string(),
  "protocol": zod.string(),
  "status": zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED']),
  "automatic_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "confirmed_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "current_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "requester_corrected": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
})

/**
 * @summary List the requester's own tickets (Tela A.2)
 */
export const ticketsControllerFindMineV1QueryPageDefault = 1;

export const ticketsControllerFindMineV1QueryPerPageDefault = 5;
export const ticketsControllerFindMineV1QueryPerPageMax = 100;



export const TicketsControllerFindMineV1QueryParams = zod.object({
  "page": zod.number().min(1).default(ticketsControllerFindMineV1QueryPageDefault),
  "perPage": zod.number().min(1).max(ticketsControllerFindMineV1QueryPerPageMax).default(ticketsControllerFindMineV1QueryPerPageDefault),
  "status": zod.array(zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED'])).optional().describe('Comma-separated list, e.g. OPEN,FORWARDED,IN_PROGRESS'),
  "resolved": zod.boolean().optional()
})

export const TicketsControllerFindMineV1Response = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "protocol": zod.string(),
  "description_summary": zod.string(),
  "current_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "status": zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED']),
  "created_at": zod.iso.datetime({"offset":true})
})),
  "page": zod.number(),
  "page_size": zod.number(),
  "total": zod.number()
})

/**
 * @summary Get ticket detail and timeline (Tela A.6)
 */
export const TicketsControllerFindOneV1Params = zod.object({
  "ticketId": zod.string()
})

export const TicketsControllerFindOneV1Response = zod.object({
  "id": zod.string(),
  "protocol": zod.string(),
  "description": zod.string(),
  "location": zod.object({
  "building": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "environment": zod.object({
  "id": zod.string(),
  "name": zod.string()
})
}),
  "photos": zod.array(zod.object({
  "id": zod.string(),
  "url": zod.string()
})),
  "status": zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED']),
  "automatic_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "confirmed_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "current_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "timeline": zod.array(zod.object({
  "type": zod.enum(['TICKET_OPENED', 'AUTO_CLASSIFIED', 'REQUESTER_CONFIRMED_SECTOR', 'REQUESTER_CHANGED_SECTOR', 'STATUS_CHANGED', 'REASSIGNED', 'TICKET_RESOLVED']),
  "description": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),
  "internal_note": zod.string().nullish()
})

/**
 * @summary Move a ticket to IN_PROGRESS or RESOLVED (Tela B.3)
 */
export const TicketsControllerUpdateStatusV1Params = zod.object({
  "ticketId": zod.string()
})

export const TicketsControllerUpdateStatusV1Body = zod.object({
  "status": zod.enum(['IN_PROGRESS', 'RESOLVED'])
})

export const TicketsControllerUpdateStatusV1Response = zod.object({
  "id": zod.string(),
  "protocol": zod.string(),
  "status": zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED']),
  "updated_at": zod.iso.datetime({"offset":true})
})

/**
 * @summary Reassign a ticket to another sector (Tela B.3)
 */
export const TicketsControllerReassignV1Params = zod.object({
  "ticketId": zod.string()
})

export const TicketsControllerReassignV1Body = zod.object({
  "target_sector_id": zod.uuid(),
  "reason": zod.string()
})

export const TicketsControllerReassignV1Response = zod.object({
  "id": zod.string(),
  "protocol": zod.string(),
  "status": zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED']),
  "previous_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "current_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "reclassified_at": zod.iso.datetime({"offset":true})
})

/**
 * @summary Set/update the sector-only internal note (Tela B.3)
 */
export const TicketsControllerUpdateInternalNoteV1Params = zod.object({
  "ticketId": zod.string()
})

export const ticketsControllerUpdateInternalNoteV1BodyInternalNoteMax = 2000;



export const TicketsControllerUpdateInternalNoteV1Body = zod.object({
  "internal_note": zod.string().max(ticketsControllerUpdateInternalNoteV1BodyInternalNoteMax)
})

export const TicketsControllerUpdateInternalNoteV1Response = zod.object({
  "success": zod.boolean(),
  "updated_at": zod.iso.datetime({"offset":true})
})

