/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List sectors with categories and responsible users (Tela C.2)
 */
export const AdminSectorsControllerFindAllV1QueryParams = zod.object({
  "search": zod.string().optional()
})

export const AdminSectorsControllerFindAllV1Response = zod.unknown()

/**
 * @summary Create a sector
 */
export const adminSectorsControllerCreateV1BodyNameMax = 255;



export const AdminSectorsControllerCreateV1Body = zod.object({
  "name": zod.string().max(adminSectorsControllerCreateV1BodyNameMax),
  "categories": zod.array(zod.string()).describe('Tags used by the automatic classifier'),
  "responsible_user_ids": zod.array(zod.uuid()).optional().describe('User UUIDs responsible for this sector')
})

export const AdminSectorsControllerCreateV1Response = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "categories": zod.array(zod.string()),
  "responsible_user_ids": zod.array(zod.string())
})

/**
 * @summary Update a sector name/categories/responsible users
 */
export const AdminSectorsControllerUpdateV1Params = zod.object({
  "sectorId": zod.string()
})

export const AdminSectorsControllerUpdateV1Body = zod.looseObject({

})

export const AdminSectorsControllerUpdateV1Response = zod.object({
  "id": zod.string(),
  "name": zod.string(),
  "categories": zod.array(zod.string()),
  "responsible_user_ids": zod.array(zod.string())
})

