import { INestApplication } from '@nestjs/common';
import { DataSource } from 'typeorm';

import { AdminSeeder, PermissionsSeeder, RolesSeeder } from '../../src/core/database/seeds';
import { UserEntity } from '../../src/modules/users/entities/user.entity';
import { ILoginAsResult, loginAs } from '../support/auth.helper';
import { ITestContainers, startContainers, stopContainers } from '../support/containers';
import { DEFAULT_PASSWORD, buildUser } from '../support/entity-factories';
import { bootstrapTestApp } from '../support/test-app.helper';
import { createTestDataSource } from '../support/test-data-source';

const ADMIN_EMAIL = 'admin@e2e-test.local';
const ADMIN_PASSWORD = 'AdminTest@123';

interface IAuditFieldChange {
  field: string;
  label: string;
  old: { value: unknown; display: string };
  new: { value: unknown; display: string };
}

interface IAuditLogResponse {
  uuid: string;
  entityName: string;
  entityLabel: string;
  entityUuid: string;
  action: string;
  actorUuid: string | null;
  createdAt: string;
  changes: IAuditFieldChange[];
}

/**
 * Audit logs are written asynchronously: `AuditSubscriber` emits an event
 * (`EventEmitter2`) from the TypeORM lifecycle, and `AuditChangeListener`
 * persists the log outside of the HTTP request/response cycle. So the log
 * for a mutation may not exist yet the instant the mutating request
 * resolves - poll for it instead of assuming it is there.
 */
async function waitForAuditLog(
  agent: ILoginAsResult['agent'],
  query: string,
): Promise<IAuditLogResponse> {
  const deadline = Date.now() + 5000;

  while (Date.now() < deadline) {
    const res = await agent.get(`/api/v1/audit-logs?${query}`);

    if (res.body.data?.data?.length > 0) {
      return res.body.data.data[0];
    }

    await new Promise((resolve) => setTimeout(resolve, 100));
  }

  throw new Error(`Timed out waiting for audit log matching "${query}"`);
}

describe('Audit (e2e)', () => {
  let containers: ITestContainers;
  let dataSource: DataSource;
  let app: INestApplication;
  let admin: ILoginAsResult;

  beforeAll(async () => {
    containers = await startContainers();
    dataSource = await createTestDataSource(containers.postgres);

    process.env.ADMIN_EMAIL = ADMIN_EMAIL;
    process.env.ADMIN_PASSWORD = ADMIN_PASSWORD;

    await new PermissionsSeeder(dataSource).run();
    await new RolesSeeder(dataSource).run();
    await new AdminSeeder(dataSource).run();

    app = await bootstrapTestApp({
      dbHost: containers.postgres.getHost(),
      dbPort: containers.postgres.getPort(),
      dbUsername: containers.postgres.getUsername(),
      dbPassword: containers.postgres.getPassword(),
      dbName: containers.postgres.getDatabase(),
      redisHost: containers.redis.getHost(),
      redisPort: containers.redis.getPort(),
    });

    admin = await loginAs(app, { email: ADMIN_EMAIL, password: ADMIN_PASSWORD });
  }, 60000);

  afterAll(async () => {
    await app.close();
    await dataSource.destroy();
    await stopContainers(containers);
  });

  describe('trail generated by a real mutation', () => {
    let targetUuid: string;
    let auditLogUuid: string;

    it('creates a user, updates its name, and eventually produces an UPDATED audit log with the old/new diff', async () => {
      const createResponse = await admin.agent
        .post('/api/v1/users')
        .set(admin.csrfHeader)
        .send({
          email: `audit-target-${Date.now()}@e2e-test.local`,
          name: 'Original Name',
          password: 'Password@123',
        })
        .expect(201);

      targetUuid = createResponse.body.data.uuid;

      await admin.agent
        .patch(`/api/v1/users/${targetUuid}`)
        .set(admin.csrfHeader)
        .send({ name: 'Updated Name' })
        .expect(200);

      const log = await waitForAuditLog(admin.agent, `entityUuid=${targetUuid}`);

      expect(log.action).toBe('UPDATED');
      expect(log.entityUuid).toBe(targetUuid);
      expect(log.entityName).toBe('user');

      const nameChange = log.changes.find((change) => change.field === 'name');

      expect(nameChange).toBeDefined();
      // `AuditPipelineService`/`FormatStage` translate the field name into a
      // human label (see `src/core/i18n/locales/pt-BR/users.json`,
      // `audit.entities.user.fields.name` -> "Nome") instead of leaving the
      // raw `name` key, and wrap each side in an `AuditValueDTO`
      // (`{ value, display }`).
      expect(nameChange?.label).toBe('Nome');
      expect(nameChange?.old.value).toBe('Original Name');
      expect(nameChange?.old.display).toBe('Original Name');
      expect(nameChange?.new.value).toBe('Updated Name');
      expect(nameChange?.new.display).toBe('Updated Name');

      auditLogUuid = log.uuid;
    });

    it('translates the entity/field labels via I18nLang, but the repo only ships one real locale (pt-BR)', async () => {
      // `I18nModule` (src/core/i18n/i18n.module.ts) only loads
      // `locales/pt-BR/*.json` and sets `fallbackLanguage: 'pt-BR'` with no
      // other locale directory present. `AcceptLanguageResolver` will try to
      // resolve `en-US`, but `I18nService` falls back to `pt-BR` for every
      // key since no `en-US` translation exists - so asserting the label
      // *differs* between `pt-BR` and `en-US` would be asserting something
      // the codebase doesn't implement. Instead this confirms translation is
      // actually happening (a real Portuguese label, not the raw field name
      // or entity name) for both header values.
      const ptResponse = await admin.agent
        .get(`/api/v1/audit-logs/${auditLogUuid}`)
        .set('Accept-Language', 'pt-BR')
        .expect(200);

      const enResponse = await admin.agent
        .get(`/api/v1/audit-logs/${auditLogUuid}`)
        .set('Accept-Language', 'en-US')
        .expect(200);

      for (const response of [ptResponse, enResponse]) {
        const body = response.body.data as IAuditLogResponse;

        expect(body.entityLabel).toBe('Usuário');

        const nameChange = body.changes.find((change) => change.field === 'name');

        expect(nameChange?.label).toBe('Nome');
      }
    });

    it('GET /audit-logs/:uuid returns 200 for a real log', async () => {
      const response = await admin.agent.get(`/api/v1/audit-logs/${auditLogUuid}`).expect(200);

      expect(response.body.data.uuid).toBe(auditLogUuid);
      expect(response.body.data.entityUuid).toBe(targetUuid);
      expect(response.body.data.action).toBe('UPDATED');
    });

    it('GET /audit-logs/:uuid returns 404 for a uuid that does not exist', async () => {
      await admin.agent.get('/api/v1/audit-logs/01965f3a-0000-7000-8000-000000000000').expect(404);
    });
  });

  describe('GET /audit-logs pagination', () => {
    it('honors page/perPage and reports pagination meta', async () => {
      // Seed a handful more logs so there is more than one page to walk.
      for (let i = 0; i < 3; i += 1) {
        await admin.agent
          .post('/api/v1/users')
          .set(admin.csrfHeader)
          .send({
            email: `audit-page-${Date.now()}-${i}@e2e-test.local`,
            name: `Page User ${i}`,
            password: 'Password@123',
          })
          .expect(201);
      }

      const firstPage = await admin.agent.get('/api/v1/audit-logs?page=1&perPage=2').expect(200);

      expect(firstPage.body.data.data).toHaveLength(2);
      expect(firstPage.body.data.meta).toEqual(expect.objectContaining({ page: 1, perPage: 2 }));
      expect(firstPage.body.data.meta.total).toBeGreaterThanOrEqual(4);

      const secondPage = await admin.agent.get('/api/v1/audit-logs?page=2&perPage=2').expect(200);

      expect(secondPage.body.data.data).toHaveLength(2);
      expect(secondPage.body.data.meta.page).toBe(2);

      const firstPageUuids = (firstPage.body.data.data as IAuditLogResponse[]).map(
        (log) => log.uuid,
      );
      const secondPageUuids = (secondPage.body.data.data as IAuditLogResponse[]).map(
        (log) => log.uuid,
      );

      for (const uuid of secondPageUuids) {
        expect(firstPageUuids).not.toContain(uuid);
      }
    });
  });

  describe('permission enforcement', () => {
    it('returns 403 for an authenticated user with no roles/permissions', async () => {
      const noRoleUser = buildUser({ email: `no-role-${Date.now()}@e2e-test.local` });

      await dataSource.getRepository(UserEntity).save(noRoleUser);

      const { agent } = await loginAs(app, {
        email: noRoleUser.email,
        password: DEFAULT_PASSWORD,
      });

      await agent.get('/api/v1/audit-logs').expect(403);
    });
  });
});
