/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List permissions
 */
export const permissionsControllerFindAllV1QueryPageDefault = 1;

export const permissionsControllerFindAllV1QueryPerPageDefault = 5;
export const permissionsControllerFindAllV1QueryPerPageMax = 100;



export const PermissionsControllerFindAllV1QueryParams = zod.object({
  "page": zod.number().min(1).default(permissionsControllerFindAllV1QueryPageDefault),
  "perPage": zod.number().min(1).max(permissionsControllerFindAllV1QueryPerPageMax).default(permissionsControllerFindAllV1QueryPerPageDefault),
  "resource": zod.string().optional().describe('Search by resource')
})

export const permissionsControllerFindAllV1ResponseOneMetaOneTotalDefault = 0;
export const permissionsControllerFindAllV1ResponseOneMetaOnePageDefault = 1;
export const permissionsControllerFindAllV1ResponseOneMetaOnePerPageDefault = 5;
export const permissionsControllerFindAllV1ResponseOneMetaOneLastPageDefault = 1;
export const permissionsControllerFindAllV1ResponseOneMetaDefault = { "total": 0 as const, "page": 1 as const, "perPage": 5 as const, "lastPage": 1 as const };

export const PermissionsControllerFindAllV1Response = zod.object({
  "meta": zod.object({
  "total": zod.number().default(permissionsControllerFindAllV1ResponseOneMetaOneTotalDefault),
  "page": zod.number().default(permissionsControllerFindAllV1ResponseOneMetaOnePageDefault),
  "perPage": zod.number().default(permissionsControllerFindAllV1ResponseOneMetaOnePerPageDefault),
  "lastPage": zod.number().default(permissionsControllerFindAllV1ResponseOneMetaOneLastPageDefault)
}).default(permissionsControllerFindAllV1ResponseOneMetaDefault)
}).and(zod.object({
  "data": zod.array(zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
})).optional()
}))

/**
 * @summary Create a new permission
 */
export const permissionsControllerCreateV1BodyResourceMax = 100;


export const permissionsControllerCreateV1BodyResourceRegExp = new RegExp('^[a-z_]+$');
export const permissionsControllerCreateV1BodyActionMax = 50;


export const permissionsControllerCreateV1BodyActionRegExp = new RegExp('^[a-z_]+$');


export const PermissionsControllerCreateV1Body = zod.object({
  "resource": zod.string().min(1).max(permissionsControllerCreateV1BodyResourceMax).regex(permissionsControllerCreateV1BodyResourceRegExp).describe('Resource this permission applies to'),
  "action": zod.string().min(1).max(permissionsControllerCreateV1BodyActionMax).regex(permissionsControllerCreateV1BodyActionRegExp).describe('Action allowed on the resource'),
  "description": zod.string().optional()
})

export const PermissionsControllerCreateV1Response = zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
})

/**
 * @summary Get permission by UUID
 */
export const PermissionsControllerFindOneV1Params = zod.object({
  "uuid": zod.string()
})

export const PermissionsControllerFindOneV1Response = zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
})

/**
 * @summary Update permission
 */
export const PermissionsControllerUpdateV1Params = zod.object({
  "uuid": zod.string()
})

export const PermissionsControllerUpdateV1Body = zod.looseObject({

})

export const PermissionsControllerUpdateV1Response = zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
})

/**
 * @summary Delete a permission
 */
export const PermissionsControllerRemoveV1Params = zod.object({
  "uuid": zod.string()
})

export const PermissionsControllerRemoveV1Response = zod.void()

