/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza — sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List roles
 */
export const rolesControllerFindAllV1QueryPageDefault = 1;

export const rolesControllerFindAllV1QueryPerPageDefault = 5;
export const rolesControllerFindAllV1QueryPerPageMax = 100;



export const RolesControllerFindAllV1QueryParams = zod.object({
  "page": zod.number().min(1).default(rolesControllerFindAllV1QueryPageDefault),
  "perPage": zod.number().min(1).max(rolesControllerFindAllV1QueryPerPageMax).default(rolesControllerFindAllV1QueryPerPageDefault),
  "search": zod.string().optional().describe('Search by role name or description')
})

export const rolesControllerFindAllV1ResponseOneMetaOneTotalDefault = 0;
export const rolesControllerFindAllV1ResponseOneMetaOnePageDefault = 1;
export const rolesControllerFindAllV1ResponseOneMetaOnePerPageDefault = 5;
export const rolesControllerFindAllV1ResponseOneMetaOneLastPageDefault = 1;
export const rolesControllerFindAllV1ResponseOneMetaDefault = { "total": 0 as const, "page": 1 as const, "perPage": 5 as const, "lastPage": 1 as const };

export const RolesControllerFindAllV1Response = zod.object({
  "meta": zod.object({
  "total": zod.number().default(rolesControllerFindAllV1ResponseOneMetaOneTotalDefault),
  "page": zod.number().default(rolesControllerFindAllV1ResponseOneMetaOnePageDefault),
  "perPage": zod.number().default(rolesControllerFindAllV1ResponseOneMetaOnePerPageDefault),
  "lastPage": zod.number().default(rolesControllerFindAllV1ResponseOneMetaOneLastPageDefault)
}).default(rolesControllerFindAllV1ResponseOneMetaDefault)
}).and(zod.object({
  "data": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isReserved": zod.boolean(),
  "permissions": zod.array(zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
}))
})).optional()
}))

/**
 * @summary Create a new role
 */
export const rolesControllerCreateV1BodyNameMin = 2;
export const rolesControllerCreateV1BodyNameMax = 100;



export const RolesControllerCreateV1Body = zod.object({
  "name": zod.string().min(rolesControllerCreateV1BodyNameMin).max(rolesControllerCreateV1BodyNameMax),
  "description": zod.string().optional()
})

export const RolesControllerCreateV1Response = zod.object({
  "uuid": zod.string(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isReserved": zod.boolean(),
  "permissions": zod.array(zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
}))
})

/**
 * @summary Get role by UUID
 */
export const RolesControllerFindOneV1Params = zod.object({
  "uuid": zod.string()
})

export const RolesControllerFindOneV1Response = zod.object({
  "uuid": zod.string(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isReserved": zod.boolean(),
  "permissions": zod.array(zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
}))
})

/**
 * @summary Update role
 */
export const RolesControllerUpdateV1Params = zod.object({
  "uuid": zod.string()
})

export const RolesControllerUpdateV1Body = zod.looseObject({

})

export const RolesControllerUpdateV1Response = zod.object({
  "uuid": zod.string(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isReserved": zod.boolean(),
  "permissions": zod.array(zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
}))
})

/**
 * @summary Delete a role
 */
export const RolesControllerRemoveV1Params = zod.object({
  "uuid": zod.string()
})

export const RolesControllerRemoveV1Response = zod.void()

/**
 * @summary Replace role permissions
 */
export const RolesControllerUpdatePermissionsV1Params = zod.object({
  "uuid": zod.string()
})

export const RolesControllerUpdatePermissionsV1Body = zod.object({
  "permissions": zod.array(zod.object({
  "resource": zod.string(),
  "action": zod.string()
})).describe('Permissions to assign to the role')
})

export const RolesControllerUpdatePermissionsV1Response = zod.object({
  "uuid": zod.string(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isReserved": zod.boolean(),
  "permissions": zod.array(zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
}))
})

/**
 * @summary Clone a role, copying its permissions into a new one
 */
export const RolesControllerCloneV1Params = zod.object({
  "uuid": zod.string()
})

export const rolesControllerCloneV1BodyNameMin = 2;
export const rolesControllerCloneV1BodyNameMax = 100;



export const RolesControllerCloneV1Body = zod.object({
  "name": zod.string().min(rolesControllerCloneV1BodyNameMin).max(rolesControllerCloneV1BodyNameMax),
  "description": zod.string().optional()
})

export const RolesControllerCloneV1Response = zod.object({
  "uuid": zod.string(),
  "name": zod.string(),
  "description": zod.string().nullish(),
  "isReserved": zod.boolean(),
  "permissions": zod.array(zod.object({
  "uuid": zod.string(),
  "resource": zod.string(),
  "action": zod.string(),
  "description": zod.string().nullish()
}))
})

