/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza — sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List imported users (Tela C.4)
 */
export const adminUsersControllerFindAllV1QueryPageDefault = 1;

export const adminUsersControllerFindAllV1QueryPerPageDefault = 5;
export const adminUsersControllerFindAllV1QueryPerPageMax = 100;

export const adminUsersControllerFindAllV1QuerySearchMax = 255;



export const AdminUsersControllerFindAllV1QueryParams = zod.object({
  "page": zod.number().min(1).default(adminUsersControllerFindAllV1QueryPageDefault),
  "perPage": zod.number().min(1).max(adminUsersControllerFindAllV1QueryPerPageMax).default(adminUsersControllerFindAllV1QueryPerPageDefault),
  "search": zod.string().max(adminUsersControllerFindAllV1QuerySearchMax).optional().describe('Filter by name or email (partial match)'),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']).optional(),
  "roleUuid": zod.uuid().optional().describe('Filter by an assigned role UUID')
})

export const adminUsersControllerFindAllV1ResponseOneMetaOneTotalDefault = 0;
export const adminUsersControllerFindAllV1ResponseOneMetaOnePageDefault = 1;
export const adminUsersControllerFindAllV1ResponseOneMetaOnePerPageDefault = 5;
export const adminUsersControllerFindAllV1ResponseOneMetaOneLastPageDefault = 1;
export const adminUsersControllerFindAllV1ResponseOneMetaDefault = { "total": 0 as const, "page": 1 as const, "perPage": 5 as const, "lastPage": 1 as const };

export const AdminUsersControllerFindAllV1Response = zod.object({
  "meta": zod.object({
  "total": zod.number().default(adminUsersControllerFindAllV1ResponseOneMetaOneTotalDefault),
  "page": zod.number().default(adminUsersControllerFindAllV1ResponseOneMetaOnePageDefault),
  "perPage": zod.number().default(adminUsersControllerFindAllV1ResponseOneMetaOnePerPageDefault),
  "lastPage": zod.number().default(adminUsersControllerFindAllV1ResponseOneMetaOneLastPageDefault)
}).default(adminUsersControllerFindAllV1ResponseOneMetaDefault)
}).and(zod.object({
  "data": zod.array(zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "institutionalId": zod.string().nullish(),
  "institutionalLink": zod.enum(['ALUNO', 'PROFESSOR', 'SERVIDOR']).nullish(),
  "status": zod.enum(['ACTIVE', 'INACTIVE', 'PENDING']),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "sectorUuids": zod.array(zod.string()),
  "createdAt": zod.iso.datetime({"offset":true})
})).optional()
}))

/**
 * @summary Download the official bulk-import spreadsheet template
 */
export const AdminUsersControllerDownloadImportTemplateV1Response = zod.unknown()

/**
 * @summary Validate and bulk-import users from a spreadsheet (RB-12: atomic)
 */
export const AdminUsersControllerImportUsersV1Body = zod.object({
  "file": zod.instanceof(Blob).optional()
})

export const AdminUsersControllerImportUsersV1Response = zod.object({
  "success": zod.boolean(),
  "error": zod.string().optional(),
  "details": zod.array(zod.looseObject({

})).optional(),
  "created": zod.number(),
  "updated": zod.number()
})

/**
 * @summary Replace a user roles and sector assignments (Tela C.4)
 */
export const AdminUsersControllerUpdatePermissionsV1Params = zod.object({
  "uuid": zod.string()
})

export const AdminUsersControllerUpdatePermissionsV1Body = zod.object({
  "roles": zod.array(zod.string()).describe('Role names to assign to the user (e.g. "ADMIN", "SECTOR", "REQUESTER")'),
  "sector_ids": zod.array(zod.uuid()).describe('Sector UUIDs the user is responsible for')
})

export const AdminUsersControllerUpdatePermissionsV1Response = zod.object({
  "id": zod.string(),
  "roles": zod.array(zod.string()),
  "sector_ids": zod.array(zod.string())
})

/**
 * @summary Revoke a user access without deleting it (RB-13)
 */
export const AdminUsersControllerRevokeV1Params = zod.object({
  "uuid": zod.string()
})

export const adminUsersControllerRevokeV1BodyReasonMax = 500;



export const AdminUsersControllerRevokeV1Body = zod.object({
  "reason": zod.string().max(adminUsersControllerRevokeV1BodyReasonMax).optional().describe('Optional audit note for why access was revoked')
})

export const AdminUsersControllerRevokeV1Response = zod.object({
  "id": zod.string(),
  "access_revoked": zod.boolean()
})

/**
 * @summary Restore a previously revoked user access
 */
export const AdminUsersControllerRestoreV1Params = zod.object({
  "uuid": zod.string()
})

export const AdminUsersControllerRestoreV1Response = zod.object({
  "id": zod.string(),
  "access_revoked": zod.boolean()
})

