/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza — sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List available sectors (Tela A.4 / Tela B.3 picker)
 */
export const SectorsControllerFindAllV1Response = zod.unknown()

