/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Research indicators: automatic accuracy, corrections, volume (Tela C.5)
 */
export const ResearchControllerIndicatorsV1QueryParams = zod.object({
  "from": zod.iso.datetime({"offset":true}).optional().describe('Period start (created_at >=), e.g. 2026-08-01'),
  "to": zod.iso.datetime({"offset":true}).optional().describe('Period end (created_at <=), e.g. 2026-08-31'),
  "sector_id": zod.uuid().optional(),
  "building_id": zod.uuid().optional()
})

export const ResearchControllerIndicatorsV1Response = zod.object({
  "automatic_accuracy": zod.object({
  "total_tickets": zod.number(),
  "correct_without_any_correction": zod.number(),
  "percentage": zod.number()
}),
  "corrections": zod.object({
  "by_requester": zod.number(),
  "by_sector": zod.number()
}),
  "time_to_correct_sector": zod.object({
  "average_minutes": zod.number(),
  "median_minutes": zod.number()
}),
  "volume": zod.object({
  "by_sector": zod.array(zod.object({
  "sector_id": zod.string(),
  "sector_name": zod.string(),
  "count": zod.number()
})),
  "by_category": zod.array(zod.object({
  "category": zod.string(),
  "count": zod.number()
})),
  "by_location": zod.array(zod.object({
  "building_id": zod.string(),
  "building_name": zod.string(),
  "count": zod.number()
}))
})
})

/**
 * @summary Export research data (classification/correction/timing) as xlsx
 */
export const ResearchControllerExportV1QueryParams = zod.object({
  "from": zod.iso.datetime({"offset":true}).optional().describe('Period start (created_at >=), e.g. 2026-08-01'),
  "to": zod.iso.datetime({"offset":true}).optional().describe('Period end (created_at <=), e.g. 2026-08-31')
})

export const ResearchControllerExportV1Response = zod.unknown()

