/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Register a push token for the authenticated device
 */
export const devicesControllerRegisterV1BodyTokenMax = 4096;



export const DevicesControllerRegisterV1Body = zod.object({
  "token": zod.string().max(devicesControllerRegisterV1BodyTokenMax),
  "platform": zod.enum(['ANDROID', 'IOS', 'WEB'])
})

export const DevicesControllerRegisterV1Response = zod.void()

/**
 * @summary Remove a push token, e.g. on logout
 */
export const devicesControllerRemoveV1BodyTokenMax = 4096;



export const DevicesControllerRemoveV1Body = zod.object({
  "token": zod.string().max(devicesControllerRemoveV1BodyTokenMax)
})

export const DevicesControllerRemoveV1Response = zod.unknown()

