/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary Login with email and password
 */




export const AuthControllerLoginV1Body = zod.object({
  "identifier": zod.string().min(1).describe('E-mail institucional ou matrícula'),
  "password": zod.string().min(1)
})

export const AuthControllerLoginV1Response = zod.object({
  "user": zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "institutionalLink": zod.enum(['ALUNO', 'PROFESSOR', 'SERVIDOR']).nullish(),
  "status": zod.string(),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "permissions": zod.array(zod.string()).describe('Effective permissions, as "resource:action"')
})
})

/**
 * @summary Refresh access token using the refresh_token cookie
 */
export const AuthControllerRefreshV1Response = zod.object({
  "user": zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "institutionalLink": zod.enum(['ALUNO', 'PROFESSOR', 'SERVIDOR']).nullish(),
  "status": zod.string(),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "permissions": zod.array(zod.string()).describe('Effective permissions, as "resource:action"')
})
})

/**
 * @summary Revoke the refresh token and clear session cookies
 */
export const AuthControllerLogoutV1Response = zod.void()

/**
 * @summary Get current authenticated user
 */
export const AuthControllerMeV1Response = zod.object({
  "uuid": zod.string(),
  "email": zod.string(),
  "name": zod.string(),
  "institutionalLink": zod.enum(['ALUNO', 'PROFESSOR', 'SERVIDOR']).nullish(),
  "status": zod.string(),
  "roles": zod.array(zod.object({
  "uuid": zod.string(),
  "name": zod.string()
})),
  "permissions": zod.array(zod.string()).describe('Effective permissions, as "resource:action"')
})

/**
 * @summary Request a password reset e-mail
 */
export const AuthControllerForgotPasswordV1Body = zod.object({
  "email": zod.email()
})

export const AuthControllerForgotPasswordV1Response = zod.void()

/**
 * @summary Reset password using the token received by e-mail
 */
export const authControllerResetPasswordV1BodyNewPasswordMin = 8;



export const AuthControllerResetPasswordV1Body = zod.object({
  "token": zod.string(),
  "newPassword": zod.string().min(authControllerResetPasswordV1BodyNewPasswordMin),
  "confirmNewPassword": zod.string()
})

export const AuthControllerResetPasswordV1Response = zod.void()

