/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza — sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List buildings with nested environments (Tela A.3 picker)
 */
export const LocationsControllerFindAllV1QueryParams = zod.object({
  "building_id": zod.uuid().optional().describe('Filter to a single building')
})

export const LocationsControllerFindAllV1Response = zod.unknown()

