/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List every ticket across all sectors (administration overview)
 */
export const adminTicketsControllerFindAllV1QueryPageDefault = 1;

export const adminTicketsControllerFindAllV1QueryPerPageDefault = 5;
export const adminTicketsControllerFindAllV1QueryPerPageMax = 100;

export const adminTicketsControllerFindAllV1QuerySearchMax = 255;



export const AdminTicketsControllerFindAllV1QueryParams = zod.object({
  "page": zod.number().min(1).default(adminTicketsControllerFindAllV1QueryPageDefault),
  "perPage": zod.number().min(1).max(adminTicketsControllerFindAllV1QueryPerPageMax).default(adminTicketsControllerFindAllV1QueryPerPageDefault),
  "sector_id": zod.uuid().optional(),
  "status": zod.array(zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED'])).optional().describe('Comma-separated list, e.g. FORWARDED,IN_PROGRESS'),
  "from": zod.iso.datetime({"offset":true}).optional().describe('Period start (created_at >=), e.g. 2026-08-01'),
  "to": zod.iso.datetime({"offset":true}).optional().describe('Period end (created_at <=), e.g. 2026-08-31'),
  "building_id": zod.uuid().optional(),
  "search": zod.string().max(adminTicketsControllerFindAllV1QuerySearchMax).optional().describe('Matches protocol, description or location (building/environment)')
})

export const AdminTicketsControllerFindAllV1Response = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "protocol": zod.string(),
  "description_summary": zod.string(),
  "current_sector": zod.object({
  "id": zod.string(),
  "name": zod.string()
}),
  "status": zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED']),
  "created_at": zod.iso.datetime({"offset":true})
})),
  "page": zod.number(),
  "page_size": zod.number(),
  "total": zod.number()
})

/**
 * @summary Aggregate volume/resolution/by-sector panel (Tela C.1)
 */
export const AdminTicketsControllerDashboardV1QueryParams = zod.object({
  "sector_id": zod.uuid().optional(),
  "status": zod.array(zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED'])).optional(),
  "from": zod.iso.datetime({"offset":true}).optional().describe('Period start (created_at >=), e.g. 2026-08-01'),
  "to": zod.iso.datetime({"offset":true}).optional().describe('Period end (created_at <=), e.g. 2026-08-31'),
  "building_id": zod.uuid().optional()
})

export const AdminTicketsControllerDashboardV1Response = zod.object({
  "summary": zod.object({
  "volume": zod.number(),
  "resolved_percentage": zod.number(),
  "average_time_to_correct_sector_minutes": zod.number()
}),
  "by_sector": zod.array(zod.object({
  "sector_id": zod.string(),
  "sector_name": zod.string(),
  "forwarded": zod.number(),
  "in_progress": zod.number(),
  "resolved": zod.number()
}))
})

