/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List the requester's own notification history (Tela A.7)
 */
export const notificationsControllerFindMineV1QueryPageDefault = 1;

export const notificationsControllerFindMineV1QueryPerPageDefault = 5;
export const notificationsControllerFindMineV1QueryPerPageMax = 100;



export const NotificationsControllerFindMineV1QueryParams = zod.object({
  "page": zod.number().min(1).default(notificationsControllerFindMineV1QueryPageDefault),
  "perPage": zod.number().min(1).max(notificationsControllerFindMineV1QueryPerPageMax).default(notificationsControllerFindMineV1QueryPerPageDefault)
})

export const NotificationsControllerFindMineV1Response = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "ticket_id": zod.string(),
  "protocol": zod.string(),
  "type": zod.enum(['TICKET_STATUS_CHANGED', 'TICKET_REASSIGNED', 'TICKET_RESOLVED']),
  "message": zod.string(),
  "created_at": zod.iso.datetime({"offset":true})
})),
  "page": zod.number(),
  "page_size": zod.number(),
  "total": zod.number()
})

