/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza - sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List audit logs
 */
export const auditControllerFindAllV1QueryPageDefault = 1;

export const auditControllerFindAllV1QueryPerPageDefault = 5;
export const auditControllerFindAllV1QueryPerPageMax = 100;



export const AuditControllerFindAllV1QueryParams = zod.object({
  "page": zod.number().min(1).default(auditControllerFindAllV1QueryPageDefault),
  "perPage": zod.number().min(1).max(auditControllerFindAllV1QueryPerPageMax).default(auditControllerFindAllV1QueryPerPageDefault),
  "entityName": zod.string().optional(),
  "entityUuid": zod.uuid().optional(),
  "actorUuid": zod.uuid().optional(),
  "action": zod.enum(['CREATED', 'UPDATED', 'DELETED']).optional()
})

export const auditControllerFindAllV1ResponseOneMetaOneTotalDefault = 0;
export const auditControllerFindAllV1ResponseOneMetaOnePageDefault = 1;
export const auditControllerFindAllV1ResponseOneMetaOnePerPageDefault = 5;
export const auditControllerFindAllV1ResponseOneMetaOneLastPageDefault = 1;
export const auditControllerFindAllV1ResponseOneMetaDefault = { "total": 0 as const, "page": 1 as const, "perPage": 5 as const, "lastPage": 1 as const };

export const AuditControllerFindAllV1Response = zod.object({
  "meta": zod.object({
  "total": zod.number().default(auditControllerFindAllV1ResponseOneMetaOneTotalDefault),
  "page": zod.number().default(auditControllerFindAllV1ResponseOneMetaOnePageDefault),
  "perPage": zod.number().default(auditControllerFindAllV1ResponseOneMetaOnePerPageDefault),
  "lastPage": zod.number().default(auditControllerFindAllV1ResponseOneMetaOneLastPageDefault)
}).default(auditControllerFindAllV1ResponseOneMetaDefault)
}).and(zod.object({
  "data": zod.array(zod.object({
  "uuid": zod.string(),
  "entityName": zod.string(),
  "entityLabel": zod.string(),
  "entityUuid": zod.string(),
  "action": zod.enum(['CREATED', 'UPDATED', 'DELETED']),
  "actorUuid": zod.string().nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "changes": zod.array(zod.object({
  "field": zod.string(),
  "label": zod.string(),
  "old": zod.object({
  "value": zod.looseObject({

}).describe('Raw/normalized value, as stored in the audit log.'),
  "display": zod.string().describe('Human-readable, translated and formatted representation.')
}),
  "new": zod.object({
  "value": zod.looseObject({

}).describe('Raw/normalized value, as stored in the audit log.'),
  "display": zod.string().describe('Human-readable, translated and formatted representation.')
})
}))
})).optional()
}))

/**
 * @summary Get audit log by UUID
 */
export const AuditControllerFindOneV1Params = zod.object({
  "uuid": zod.string()
})

export const AuditControllerFindOneV1Response = zod.object({
  "uuid": zod.string(),
  "entityName": zod.string(),
  "entityLabel": zod.string(),
  "entityUuid": zod.string(),
  "action": zod.enum(['CREATED', 'UPDATED', 'DELETED']),
  "actorUuid": zod.string().nullish(),
  "createdAt": zod.iso.datetime({"offset":true}),
  "changes": zod.array(zod.object({
  "field": zod.string(),
  "label": zod.string(),
  "old": zod.object({
  "value": zod.looseObject({

}).describe('Raw/normalized value, as stored in the audit log.'),
  "display": zod.string().describe('Human-readable, translated and formatted representation.')
}),
  "new": zod.object({
  "value": zod.looseObject({

}).describe('Raw/normalized value, as stored in the audit log.'),
  "display": zod.string().describe('Human-readable, translated and formatted representation.')
})
}))
})

