/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Sinaliza API
 * API do Sinaliza — sistema de chamados universitário
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';


/**
 * @summary List the caller's sector queue(s) (Telas B.2/B.4)
 */
export const sectorTicketsControllerFindAllV1QueryPageDefault = 1;

export const sectorTicketsControllerFindAllV1QueryPerPageDefault = 5;
export const sectorTicketsControllerFindAllV1QueryPerPageMax = 100;

export const sectorTicketsControllerFindAllV1QuerySearchMax = 255;

export const sectorTicketsControllerFindAllV1QueryOrderDefault = `asc`;

export const SectorTicketsControllerFindAllV1QueryParams = zod.object({
  "page": zod.number().min(1).default(sectorTicketsControllerFindAllV1QueryPageDefault),
  "perPage": zod.number().min(1).max(sectorTicketsControllerFindAllV1QueryPerPageMax).default(sectorTicketsControllerFindAllV1QueryPerPageDefault),
  "sector_id": zod.uuid().optional().describe('Restrict to one of the caller-visible sectors'),
  "status": zod.array(zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED'])).optional().describe('Comma-separated list, e.g. FORWARDED,IN_PROGRESS'),
  "from": zod.iso.datetime({"offset":true}).optional().describe('Period start (created_at >=), e.g. 2026-08-01'),
  "to": zod.iso.datetime({"offset":true}).optional().describe('Period end (created_at <=), e.g. 2026-08-31'),
  "building_id": zod.uuid().optional(),
  "search": zod.string().max(sectorTicketsControllerFindAllV1QuerySearchMax).optional().describe('Matches protocol, description or location (building/environment)'),
  "order": zod.enum(['asc', 'desc']).default(sectorTicketsControllerFindAllV1QueryOrderDefault)
})

export const SectorTicketsControllerFindAllV1Response = zod.object({
  "items": zod.array(zod.object({
  "id": zod.string(),
  "protocol": zod.string(),
  "description_summary": zod.string(),
  "location": zod.string(),
  "status": zod.enum(['OPEN', 'FORWARDED', 'IN_PROGRESS', 'RESOLVED']),
  "automatic_sector_id": zod.string(),
  "confirmed_sector_id": zod.string(),
  "classification_diverged": zod.boolean(),
  "created_at": zod.iso.datetime({"offset":true})
})),
  "page": zod.number(),
  "page_size": zod.number(),
  "total": zod.number()
})

